.\" 
.\" groff -man -Tascii name_of_file
.\"
.TH libm3l 1 "June 2012" libm3l "User Manuals"
.SH NAME
m3l_Send_receive_tcpipsocket \- send list to socket and receives list from a socket
.SH SYNOPSIS

#include <libm3l.h>

.B node_t *m3l_Send_receive_tcpipsocket
(node_t *Lnode, const char *hostname, int portnumber, char * Options, ...)


.SH DESCRIPTION
.B m3l_Send_receive_tcpipsocket
send list Lnode to socket with a hostname and port number and reads 
list from a socket
.
.

.SH OPTIONS
.IP "-e --clean_empy_links"
If the file contains links which are empty, remove them
.IP "-c --encoding <value>"
Encoding of floating point numbers before ending them over the socket. If value is 
.B text 
the floating point numbers are converted to text. If the value is 
.B IEEE-754
the floating point numbers encodes according to IEEE-754 specifrications
.IP "-b --buffering <value>"
writing and reading numbers from/to buffer 
.B SPRINRF 
use snprintf function for writing and stroul type of function for reading
.B MEMCPY
use MEMCPY function
.IP -E --EOB
send EOFbuff sequence only, Lnode is ignored
.IP "-s --shutdown"
shuts down the socket for sending when sending list is finsihed.


.SH RETURN VALUE
Upon successful completion m3l_Send_receive_tcpipsocket will pointer to received list. Otherwise, it shall return NULL.

.SH ERRORS
The m3l_Send_receive_tcpipsocket function fails if socket does not exist

.SH CHANGE HISTORY
none

.SH AUTHOR
Adam Jirasek <libm3l at google dot com>
.SH "SEE ALSO"
.BH shutdown

