.\" 
.\" groff -man -Tascii name_of_file
.\"
.TH libm3l 1 "June 2012" libm3l "User Manuals"
.SH NAME
m3l_get_List_dim \- return data dimensions
.SH SYNOPSIS

#include <libm3l.h>

.B size_t *m3l_get_List_dim
(node_t *List)



.SH DESCRIPTION
.B m3l_get_List_dim
Function returns pointer to vector of data dimensions (ie. List->fdim)
.

.SH OPTIONS
none


.SH RETURN VALUE
Upon successful the function returns pointer to List->fdim.

.SH ERRORS


.SH CHANGE HISTORY
none

.SH AUTHOR
Adam Jirasek <libm3l at google dot com>
.SH "SEE ALSO"
.BR m3l_Mklist
