.\" 
.\" groff -man -Tascii name_of_file
.\"
.TH libm3l 1 "June 2012" libm3l "User Manuals"
.SH NAME
m3l_get_List_ndim \- returns data dimensions
.SH SYNOPSIS

#include <libm3l.h>

.B size_t m3l_get_List_ndim
(node_t *List)



.SH DESCRIPTION
.B m3l_get_List_ndim
Function returns size of data dimensions (ie. List->ndim)
.

.SH OPTIONS
none


.SH RETURN VALUE
Upon successful the function returns number of dimensions for List data array

.SH ERRORS


.SH CHANGE HISTORY
none

.SH AUTHOR
Adam Jirasek <libm3l at google dot com>
.SH "SEE ALSO"
.BR 
