.\" 
.\" groff -man -Tascii name_of_file
.\"
.TH libm3l 1 "June 2012" libm3l "User Manuals"
.SH NAME
m3l_server_openbindlistensocket \- opens, binds socket and convert it to listening socket
.SH SYNOPSIS

#include <libm3l.h>

.B node_t *m3l_server_openbindlistensocket
(int portnumber, char* Options, ....)


.SH DESCRIPTION
.B m3l_server_openbindlistensocket
opens socket with port number portno, binds socket and convert it to listening socket
.
.

.SH OPTIONS
none

.SH RETURN VALUE
Upon successful completion m3l_server_openbindlistensocket will socket descriptor. Otherwise, it shall return negative value.

.SH ERRORS
The m3l_server_openbindlistensocket function fails if socket operations fail

.SH CHANGE HISTORY
none

.SH AUTHOR
Adam Jirasek <libm3l at google dot com>
.SH "SEE ALSO"

