.\" 
.\" groff -man -Tascii name_of_file
.\"
.TH libm3l 1 "June 2012" libm3l "User Manuals"
.SH NAME
m3l_get_Found_number \- finds number of items in find_t struture
.SH SYNOPSIS

#include <libm3l.h>

.B size_t m3l_get_Found_number
(find_t *Found)



.SH DESCRIPTION
.B m3l_m3l_get_Found_number
Function returns number of items in Found structure (ie. Founds->founds)
.

.SH OPTIONS
none


.SH RETURN VALUE
Upon successful the function returns number of items in Found structure

.SH ERRORS


.SH CHANGE HISTORY
none

.SH AUTHOR
Adam Jirasek <libm3l at google dot com>
.SH "SEE ALSO"
.BR m3l_Mklist
